### ISSUE TITLE
Add suppression option for print messages during training loop?

### ISSUE THREAD

**Issue by ir5** [pfnet/chainerrl#32]
In `chainerrl.experiments.train_agent`, statistical information is reported via `print` per episode during the training loop. However, this sometimes looks so verbose and I want to suppress these messages, but currently there is no good way to do so. Adding some option that enables/disables these prints might be beneficial.

**Comment by muupan** [comment]
I agree. I think adding an option to suppress them is OK, but using logger instead of print might be more flexible.
