### ISSUE TITLE
The tutorial code causes TypeError on python 3.4

### ISSUE THREAD

**Issue by knok** [pfnet/chainerrl#36]
On python 3.4, random.sample don't accept collections.deque, so I got such error.

```py3
Traceback (most recent call last):
  File "quickstart.py", line 111, in <module>
    action = agent.act_and_train(obs, reward)
  File "/opt/rl/lib/python3.4/site-packages/chainerrl/agents/dqn.py", line 340, in act_and_train
    self.replay_updator.update_if_necessary(self.t)
  File "/opt/rl/lib/python3.4/site-packages/chainerrl/replay_buffer.py", line 194, in update_if_necessary
    transitions = self.replay_buffer.sample(self.batchsize)
  File "/opt/rl/lib/python3.4/site-packages/chainerrl/replay_buffer.py", line 42, in sample
    return random.sample(self.memory, n)
  File "/opt/rl/lib/python3.4/random.py", line 311, in sample
    raise TypeError("Population must be a sequence or set.  For dicts, use list(d).")
TypeError: Population must be a sequence or set.  For dicts, use list(d).
```

python 2.7 works fine, and meybe 3.5+.

**Comment by muupan** [comment]
Thanks for reporting the error! ChainerRL currently doesn't work with Python 3.4 but it was not documented. I've just add tested python versions in README.md.

**Comment by knok** [comment]
Thank you for your responce.
I think, modifing to "random.shuffe(list(self.memory), n) " in ReplayBuffer.sample() would
be a workaround, do you have a plan to suppor older python?

The workaround will affect to performance, so older python support is just my hope,
I will not clame it must be.

**Comment by muupan** [comment]
I don't have a plan to support python 3.4 for now, but contributions to support it are welcome. I'm curious when people need to use python 3.4.

**Comment by knok** [comment]
I see. I can't make more effiective way to adopt older python, so I'll use 3.5+.
Thank you.

**Comment by knorth55** [comment]
I had same problem with `python3.4.3` on `Ubuntu 14.04`.
I made a PR #128
