### ISSUE TITLE
Question on gym action space

### ISSUE THREAD

**Issue by emrul** [pfnet/chainerrl#56]
Hi, I've defined my own OpenAI gym and have specified my actions in the environment as follows:

`
self.actions = ["NOOP", "LEFT", "RIGHT", "FIRE", "CLOAK"]

self.action_space = spaces.Discrete(len(self.actions))
`

When I try my environment against the 'train_dqn_gym.py' example I can see from my debug output that the training is correctly resulting in trying a variety of different actions.

However, with both 'train_a3c_gym.py' and 'train_acer_gym.py' the action value provided to my step value is always 0 (NOOP) - it never tries any other action.

Have I coded something wrong in my environment? I would appreciate any tips on how to investigate my issue further.

**Comment by muupan** [comment]
Hi, can you paste your code and its debug output?

**Comment by emrul** [comment]
I have isolated the problem: my observation space has some NaNs in it (which were erroneous).  Once I fixed the NaNs from happening then ACER and A3C begin to explore more of the action space.  Please go ahead and close this issue (unless presence of NaN values should not be causing such an issue, I'm not experienced enough to know)

**Comment by muupan** [comment]
That makes sense. NaN in observations would result in NaN in outputs of a policy or a value function.
