### ISSUE TITLE
Date and time format for experiments

### ISSUE THREAD

**Issue by toslunar** [pfnet/chainerrl#61]
Human-readability of the name of the subdirectory for an experiment might be improved.  The current imprementation (`time_str = datetime.datetime.now().strftime('%Y%m%d%H%M%S%f')` in chainerrl/experiments/prepare_output_dir.py) produces e.g. 21120903182945898662.  How about
- `strftime('%Y%m%d-%H%M%S-%f')` (e.g. 21120903-182945-898662), or
- the basic format in ISO 8601 (e.g. 21120903T182945.898662+0900)?

**Comment by muupan** [comment]
I think both are fine for a default format, and `prepare_output_dir` should accept a format string as an optional argument so users can customize the format.
