### ISSUE TITLE
Visualization of models?

### ISSUE THREAD

**Issue by kfeeeeee** [pfnet/chainerrl#63]
Is there an existing method to visualize models?

**Comment by muupan** [comment]
What do you mean by "visualize models"? It is possible to load a trained model and run it with some rendering i.e. env.render of gym envs.

**Comment by kfeeeeee** [comment]
I was trying to save a graphical representation of the model (as an image).

**Comment by muupan** [comment]
For gym envs, `gym.wrappers.Monitor` is available to record a video of envs. For ALE, you can specify `record_screen_dir` argument to save screens as image files.

**Comment by kfeeeeee** [comment]
Thanks again, I was looking for a possibility to save the chainer model used e.g. as the q function as an image. I found a way to do this but this not relevant for chainerrl but chainer.
