### ISSUE TITLE
Examples for stateful q learning and a3c

### ISSUE THREAD

**Issue by kfeeeeee** [pfnet/chainerrl#65]
Would it be possible to provide examples for stateful models for q learning and a3c?

**Comment by muupan** [comment]
You mean recurrent models? If so, there is an A3C example that use an LSTM. https://github.com/pfnet/chainerrl/blob/master/examples/ale/train_a3c_ale.py

It is also possible to use recurrent models in DQN in a similar way, but unfortunately there's no example for now.

**Comment by kfeeeeee** [comment]
Yes, this is exactly what I mean. The a3c example you mentioned did not work for me (train_a3c_gym.py) on CartPole-v0 - does this only work for continous action spaces? I am fairly new to chainer and RL in general so please be gently :)

**Comment by kfeeeeee** [comment]
After a bit of digging I figured it out. You may close this, pls.
